### ISSUE TITLE
Add Property action just saves the datatype

### ISSUE THREAD

**Issue by ryanmcdonough** [Lecoati/LeBlender#54]
When I create a new LeBlender editor I go to press 'Add Property' it just saves the datatype and I get this error in the console:

angular.min.js?cdv=665052652:63 TypeError: Cannot read property 'config' of undefined
    at new <anonymous> (leblenderproperties.controller.js?cdv=665052652:8)
    at d (angular.min.js?cdv=665052652:28)
    at Object.instantiate (angular.min.js?cdv=665052652:28)
    at angular.min.js?cdv=665052652:53
    at angular.min.js?cdv=665052652:44
    at n (angular.min.js?cdv=665052652:7)
    at k (angular.min.js?cdv=665052652:44)
    at e (angular.min.js?cdv=665052652:40)
    at angular.min.js?cdv=665052652:39
    at angular.min.js?cdv=665052652:158

Tried hard cache clear and refresh, and the issue persists when closing and re-opening a saved datatype.

Tried 1.0.8.4 had the issue, then tried 1.0.7 - same problem. Running against: 7.4.3

**Comment by ryanmcdonough** [comment]
Making the wrong type of editor.

**Comment by FDBenevides** [comment]
Hi @ryanmcdonough,

Can you please clarify a little more what were you doing wrong and what solved the issue?
Because I've installed the LeBlender using nuget in VS and I can't see the GridEditors in the Developer Section in the backoffice. And I also have that same behaviour with the "add property" button and the javascript error in the console.

Thanks

**Comment by ryanmcdonough** [comment]
@FDBenevides Yeah you need to create the editor within the Grid Editors section in the developer area, creating it within the Data Types caused the issue above.

I would suggest checking leblender definitely installed with nuget, or clearing browser cache and seeing if the Grid Editors section appears within developer.

**Comment by FDBenevides** [comment]
Thanks @ryanmcdonough for confirming that. I was suspecting that it was missing some "configuration" when used within the Data Types.
So my problem still persists...because it doesn't show up within the Developers section :(

I'm using the LeBlender version 1.0.8.4, installed with nuget. 
Can you please copy here the line in your trees.config file related to LeBlender?

Thanks again!

**Comment by FDBenevides** [comment]
forget it @ryanmcdonough  :D 
I've tried to install it again and it's working now :) 

Still...I don't know what was the problem before... :)
