### ISSUE TITLE
LeBlender is awesome, but is the project dead?

### ISSUE THREAD

**Issue by kipusoep** [Lecoati/LeBlender#70]
There hasn't been any recent updates, but I couldn't use the Grid without LeBlender.
So is the project dead?

**Comment by Dan9boi** [comment]
Hi @kipusoep 
We know that it's been a looooong time since last update on the leblender project, and we see all of the issues and pr's.
But i can promise you that we will start doing awesome stuff on the project very soon!

Best regards
Danni

**Comment by lukefrake** [comment]
Hi @Dan9boi !

I was wondering exactly this, we currently can't upgrade projects to the latest Umbraco as they depend on LeBlender. We're at a crossroads and are going to have to change away from LeBlender. It seems PRs don't get reviewed or merged either.
Do you have a roadmap to explain how soon is soon?

All the best,
Luke

**Comment by soreng** [comment]
Hi Luke,

What kind of issues do you have? We have used LeBlender on every version of Umbraco since it was first released.

We are looking into all issues an PRs, but there is no timeline ATM. The first task is to prioritize the work, after that we may release a roadmap, if needed.

Otherwise please comment/vote in the bugs that cause you trouble, so they get a higher priority:-)

Regards,
Søren

**Comment by soreng** [comment]
@lukefrake we made a few changes today, that we will be testing, before pushing a new version to nuget :)

**Comment by bjarnef** [comment]
@soreng unfortunately we find the latest v1.9.0.2 more buggy than the existing v.1.8.04
https://github.com/Lecoati/LeBlender/issues/86
https://github.com/Lecoati/LeBlender/issues/87

Please also notice the missing release of an Umbraco package for the same version.

**Comment by saadan** [comment]
So any news ? Is it dead now ? 🤔
